version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hrms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hrms
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_secret_2026
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
